apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicontratos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apicontratos
  template:
    metadata:
      labels:
        app: apicontratos
    spec:
      containers:
      - name: apicontratos
        image: thiagodarlei/apicontratos:1.0
        env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: contratosdb
          - name: DB_USER
            value: apiuser
          - name: DB_PASS
            value: apipass
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apicontratos-service
spec:
  type: NodePort
  selector:
    app: apicontratos
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080