services:
  mysql:
    image: mysql:8.0
    container_name: mysql-contratos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contratosdb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  apicontratos:
    build: .
    container_name: apicontratos
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: contratosdb
      DB_USER: apiuser
      DB_PASS: apipass
    ports:
      - "8080:8080"

volumes:
  mysql_data:
