# ==========================
# PVC para MySQL
# Reserva 1Gi de armazenamento persistente
# ==========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# ==========================
# DEPLOYMENT MYSQL
# Banco de dados MySQL com volume persistente
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1 # geralmente apenas 1 réplica para banco de dados
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
          - containerPort: 3306
        env: # variáveis de ambiente lidas do ConfigMap/Secret
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: contratos-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: contratos-config
                key: DB_NAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: contratos-secret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: contratos-secret
                key: DB_PASS
        volumeMounts:
          - mountPath: /var/lib/mysql # caminho onde os dados ficam
            name: mysql-storage
        resources: # solicitações e limites de CPU/memória
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
# ==========================
# SERVICE MYSQL
# Service interno para acesso da API ao banco
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306 # porta interna do service
      targetPort: 3306 # porta do container
